"""add businesses table

Revision ID: 3379ac35ea78
Revises: 1d7af2786390
Create Date: 2026-03-07 12:19:17.758281

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3379ac35ea78"
down_revision: str | Sequence[str] | None = "1d7af2786390"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scraping_job_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("zone", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("google_maps_url", sa.String(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scraping_job_id"], ["scraping_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_businesses_category"), "businesses", ["category"], unique=False)
    op.create_index(
        op.f("ix_businesses_scraping_job_id"), "businesses", ["scraping_job_id"], unique=False
    )
    op.create_index(op.f("ix_businesses_zone"), "businesses", ["zone"], unique=False)
    op.create_index("ix_businesses_category_zone", "businesses", ["category", "zone"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_businesses_zone"), table_name="businesses")
    op.drop_index(op.f("ix_businesses_scraping_job_id"), table_name="businesses")
    op.drop_index("ix_businesses_category_zone", table_name="businesses")
    op.drop_index(op.f("ix_businesses_category"), table_name="businesses")
    op.drop_table("businesses")
    # ### end Alembic commands ###
